{
  perform: true,
  alwaysRequireAssignee: true,
  defaultAssignee: 'anthonydresser',
  defaultLabel: 'Triage: Needed',
  labelsRequiringAssignee: [],
  autoAssignees: {
    Area - Acquisition: [],
    Area - Azure: [],
    Area - Backup\Restore: [],
    Area - Charting\Insights: [],
    Area - Connection: [],
    Area - DacFX: [],
    Area - Dashboard: [],
    Area - Data Explorer: [],
    Area - Edit Data: [],
    Area - Extensibility: [],
    Area - External Table: [],
    Area - Fundamentals: [],
    Area - Language Service: [],
    Area - Localization: [],
    Area - Notebooks: [ ],
    Area - Performance: [],
    Area - Query Editor: [ ],
    Area - Query Plan: [],
    Area - Reliability: [],
    Area - Resource Deployment: [],
    Area - Schema Compare: [],
    Area - Shell: [],
    Area - SQL Agent: [],
    Area - SQL Import: [],
    Area - SQL Profiler: [],
    Area - SQL 2019: [],
    Area - SSMS Integration: []
  }
}
