{
    perform: true,
    commands: [
        {
            type: 'comment',
            name: 'question',
            action: 'updateLabels',
            addLabel: '*question'
        },
        {
            type: 'label',
            name: '*not-reproducible',
            action: 'close',
            comment: "We closed this issue because we are unable to reproduce the problem with the steps you describe. Chances are we've already fixed your problem in a recent version of Azure Data Studio. If not, please ask us to reopen the issue and provide us with more detail. Our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines might help you with that.\n\nHappy Coding!"
        },
        {
            type: 'label',
            name: '*out-of-scope',
            action: 'close',
            comment: "This issue is being closed to keep the number of issues in our inbox on a manageable level, we are closing issues that are not going to be addressed in the foreseeable future: We look at the number of votes the issue has received and the number of duplicate issues filed. If you disagree and feel that this issue is crucial: We are happy to listen and to reconsider.\n\nIf you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.\n\nThanks for your understanding and happy coding!"
        },
        {
            type: 'label',
            name: '*caused-by-extension',
            action: 'close',
            comment: "This issue is caused by an extension, please file it with the repository (or contact) the extension has linked in its overview in Azure Data Studio or the [marketplace](https://aka.ms/vscodemarketplace) for Azure Data Studio. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.\n\nHappy Coding!"
        },
        {
            type: 'comment',
            name: 'duplicate',
            action: 'updateLabels',
            addLabel: '*duplicate'
        },
        {
            type: 'label',
            name: '*duplicate',
            allowTriggerByBot: true,
            action: 'close',
            comment: "Thanks for creating this issue! We figured it's covering the same as another one we already have. Thus, we closed this one as a duplicate. You can search for existing issues [here](https://aka.ms/vscodeissuesearch). See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.\n\nHappy Coding!"
        },
        {
            type: 'comment',
            name: 'confirm',
            allowUsers: ['cleidigh', 'usernamehw'],
            action: 'updateLabels',
            addLabel: 'confirmed',
            removeLabel: 'confirmation-pending'
        },
        {
            type: 'comment',
            name: 'confirmationPending',
            allowUsers: ['cleidigh', 'usernamehw'],
            action: 'updateLabels',
            addLabel: 'confirmation-pending',
            removeLabel: 'confirmed'
        },
        {
            type: 'comment',
            name: 'findDuplicates',
            action: 'comment',
            comment: "Potential duplicates:\n${potentialDuplicates}"
        },
        {
            type: 'comment',
            name: 'needsMoreInfo',
            action: 'updateLabels',
            addLabel: 'needs more info',
            comment: "Thanks for creating this issue! We figured it's missing some basic information or in some other way doesn't follow our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines. Please take the time to review these and update the issue.\n\nHappy Coding!"
        },
        {
            type: 'comment',
            name: 'a11ymas',
            allowUsers: ['notquiteme'],
            action: 'updateLabels',
            addLabel: 'a11ymas'
        },
        ################### Work in progress ###################
        {
            type: 'label',
            name: 'integrated-terminal',
            allowTriggerByBot: true,
            action: 'updateLabels',
            addLabel: '*confirmation-needed'
        },
        {
            type: 'label',
            name: '*confirmation-needed',
            allowTriggerByBot: true,
            action: 'comment',
            comment: "Our issue tracking requires confirmation by a second community member. Anyone but OP can do so by adding a comment `/confirm`. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.\n\nHappy Coding!"
        },
        {
            type: 'comment',
            name: 'confirm',
            allowUsers: ['notquiteme'],
            action: 'updateLabels',
            removeLabel: '*confirmation-needed',
            addLabel: 'confirmed'
        },
        {
            type: 'label',
            name: 'Needs Logs',
            action: 'comment',
            comment: "We need more info to debug your particular issue. If you could attach your logs to the issue (ensure no private data is in them), it would help us fix the issue much faster.\n\nTo find your logs:\n\n- Open command palette (Click **View** -> **Command Palette**)\n- Run the command: **`Developer: Open Logs Folder`**\n\nThis will open the log file locally. Please include renderer.log"
        }
    ]
}
